### ISSUE TITLE
make onConnectionError public

### ISSUE THREAD

**Issue by NicoM1** [Dvergar/Anette#2]
as title; handy for stuff like spawning a server if one doesn't exist (this may be terrible practice, I've never tried networking until today, and haven't read any articles recently or very thoroughly, this is just what I thought of.)

Nico

**Comment by Dvergar** [comment]
I probably need a more streamlined way to handle errors across platforms, but that should do it for cpp/neko for now. Thanks for reporting, should have been exposed earlier. I used the same API than the rest of event handlers though.

`client.onConnectionError = onMyConnectionHandlerError;` with a `Dynamic->Void` signature.

(I added it in the samples)

**Comment by NicoM1** [comment]
sweet thanks:D btw can you tell me (or point me to an article) how to take something that works on the localhost and connect it across LAN/real internet? I have no idea what to search for....

thanks,
Nico

**Comment by NicoM1** [comment]
hah, didn't even notice that I never had to change anything after updating anette, because my quick fix was making onConnectionError a dynamic function, so the API was exactly the same as when you added it
